name: Releases

on:
  release:
    types:
      - released

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Notify changelog of new release
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
          repository: box/box-developer-changelog
          event-type: release
          client-payload: '{"ref": "${{ github.ref }}", "repository": "${{github.repository}}", "tags": "test,actions", "template": "Test %s released"}'